/**
 * widget-generator (v0.1)
 *
 * Takes a WidgetSchema and produces three TypeScript/TSX files:
 *   1. <WidgetName>.types.ts    — Props interface
 *   2. <WidgetName>.metadata.ts — Sitefinity-compatible metadata
 *   3. <WidgetName>.tsx         — React component
 */

import type { WidgetSchema, GeneratedWidget, WidgetProperty, PropertyType } from "@/types/widget";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function tsType(type: PropertyType, isNullable?: boolean): string {
  const base: Record<PropertyType, string> = {
    string: "string",
    number: "number",
    boolean: "boolean",
    "string[]": "string[]",
    "number[]": "number[]",
    unknown: "unknown",
  };
  const t = base[type] ?? "unknown";
  return isNullable ? `${t} | null` : t;
}

function docComment(lines: string[]): string {
  if (!lines.length) return "";
  return `/**\n${lines.map((l) => ` * ${l}`).join("\n")}\n */\n`;
}

// ---------------------------------------------------------------------------
// 1. Types file
// ---------------------------------------------------------------------------

function generateTypesFile(schema: WidgetSchema): string {
  const { widgetName, properties } = schema;

  const propLines = properties
    .map((p) => {
      const comment = p.description ? `  /** ${p.description} */\n` : "";
      const optional = p.isNullable ? "?" : "";
      return `${comment}  ${p.camelName}${optional}: ${tsType(p.type, p.isNullable)};`;
    })
    .join("\n");

  return `// Auto-generated by Sitefinity Widget Studio
// Source: ${schema.className}
// Do not edit manually — re-run the converter to update.

export interface ${widgetName}Props {
${propLines}
}
`;
}

// ---------------------------------------------------------------------------
// 2. Metadata file
// ---------------------------------------------------------------------------

function generateMetadataFile(schema: WidgetSchema): string {
  const { widgetName, properties } = schema;

  const metaEntries = properties
    .map((p) => {
      const lines: string[] = [`    type: "${p.type}"`];
      if (p.displayName) lines.push(`    displayName: "${p.displayName}"`);
      if (p.description) lines.push(`    description: "${p.description}"`);
      if (p.defaultValue !== undefined && p.defaultValue !== null) {
        const val =
          typeof p.defaultValue === "string"
            ? `"${p.defaultValue}"`
            : String(p.defaultValue);
        lines.push(`    defaultValue: ${val}`);
      }
      if (p.section) lines.push(`    section: "${p.section}"`);
      return `  ${p.camelName}: {\n${lines.join(",\n")},\n  }`;
    })
    .join(",\n");

  return `// Auto-generated by Sitefinity Widget Studio
// Source: ${schema.className}

import type { ${widgetName}Props } from "./${widgetName}.types";

export interface ${widgetName}MetaProperty {
  type: string;
  displayName?: string;
  description?: string;
  defaultValue?: unknown;
  section?: string;
}

export const ${widgetName[0].toLowerCase() + widgetName.slice(1)}Metadata: Record<
  keyof ${widgetName}Props,
  ${widgetName}MetaProperty
> = {
${metaEntries},
};
`;
}

// ---------------------------------------------------------------------------
// 3. Component file
// ---------------------------------------------------------------------------

/**
 * Generates a minimal but usable React component.
 * Each property gets a sensible default render based on its type.
 */
function generateComponentFile(schema: WidgetSchema): string {
  const { widgetName, properties } = schema;

  const renderBody = buildRenderBody(properties);

  return `// Auto-generated by Sitefinity Widget Studio
// Source: ${schema.className}
// Tip: Customise the JSX below — this is just the scaffold.

import type { ${widgetName}Props } from "./${widgetName}.types";

export default function ${widgetName}(props: ${widgetName}Props) {
  return (
    <section className="py-16">
      <div className="container mx-auto px-6 max-w-5xl">
${renderBody}
      </div>
    </section>
  );
}
`;
}

function buildRenderBody(properties: WidgetProperty[]): string {
  const lines: string[] = [];

  // Find common widget patterns
  const titleProp = properties.find((p) =>
    /^(title|heading|headline)$/i.test(p.camelName)
  );
  const subtitleProp = properties.find((p) =>
    /^(subtitle|subheading|description|body|text|content)$/i.test(p.camelName)
  );
  const buttonTextProp = properties.find((p) =>
    /^(buttonText|ctaText|linkText)$/i.test(p.camelName)
  );
  const buttonUrlProp = properties.find((p) =>
    /^(buttonUrl|ctaUrl|linkUrl|href|url)$/i.test(p.camelName)
  );
  const showButtonProp = properties.find((p) =>
    /^(showButton|showCta|showLink)$/i.test(p.camelName)
  );

  const handled = new Set<string>();

  if (titleProp) {
    lines.push(`        <h2 className="text-4xl font-bold mb-4">{props.${titleProp.camelName}}</h2>`);
    handled.add(titleProp.camelName);
  }

  if (subtitleProp) {
    lines.push(`        <p className="text-lg text-gray-600 mb-8">{props.${subtitleProp.camelName}}</p>`);
    handled.add(subtitleProp.camelName);
  }

  if (buttonTextProp && buttonUrlProp) {
    const showCondition = showButtonProp
      ? `props.${showButtonProp.camelName} && `
      : "";
    lines.push(
      `        {${showCondition}(`
    );
    lines.push(
      `          <a`
    );
    lines.push(`            href={props.${buttonUrlProp.camelName}}`);
    lines.push(
      `            className="inline-flex items-center px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"`
    );
    lines.push(`          >`);
    lines.push(`            {props.${buttonTextProp.camelName}}`);
    lines.push(`          </a>`);
    lines.push(`        )}`);
    handled.add(buttonTextProp.camelName);
    handled.add(buttonUrlProp.camelName);
    if (showButtonProp) handled.add(showButtonProp.camelName);
  }

  // Render remaining properties as generic output
  const remaining = properties.filter((p) => !handled.has(p.camelName));

  if (remaining.length > 0 && lines.length > 0) {
    lines.push(`        {/* Additional properties */}`);
  }

  for (const prop of remaining) {
    if (prop.type === "boolean") {
      lines.push(
        `        {props.${prop.camelName} && <span className="text-sm text-gray-500">${prop.displayName ?? prop.name}: on</span>}`
      );
    } else if (prop.type === "string" || prop.type === "number") {
      lines.push(
        `        <p className="text-sm text-gray-500">{props.${prop.camelName}}</p>`
      );
    }
  }

  if (lines.length === 0) {
    lines.push(`        <p className="text-gray-400">{/* No renderable properties detected */}</p>`);
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function generateWidget(schema: WidgetSchema): GeneratedWidget {
  const { widgetName } = schema;

  return {
    typesFile: {
      filename: `${widgetName}.types.ts`,
      content: generateTypesFile(schema),
    },
    metadataFile: {
      filename: `${widgetName}.metadata.ts`,
      content: generateMetadataFile(schema),
    },
    componentFile: {
      filename: `${widgetName}.tsx`,
      content: generateComponentFile(schema),
    },
  };
}
