/**
 * widget-generator (v0.3)
 *
 * Takes a WidgetSchema (from either parser) and produces:
 *   1. <widget-name>.entity.ts  — SDK entity class with decorators (v0.3, primary)
 *   2. <widget-name>.tsx        — SDK component with htmlAttributes (v0.3, primary)
 *   3. registryEntrySnippet     — snippet to paste into widget-registry.ts (v0.3)
 *   4. <WidgetName>.types.ts    — @deprecated flat Props interface (v0.2)
 *   5. <WidgetName>.metadata.ts — @deprecated metadata object (v0.2)
 */

import type {
  WidgetSchema,
  GeneratedWidget,
  PropertyType,
  NestedObjectShape,
} from "@/types/widget";
import { generateEntityFile } from "@/lib/generator-nextjs-entity";
import { generateNextjsComponent } from "@/lib/generator-nextjs-component";
import { generateRegistryEntry } from "@/lib/generator-widget-registry-entry";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function tsType(type: PropertyType, nestedShape?: NestedObjectShape, isNullable?: boolean): string {
  let base: string;
  if (type === "object" && nestedShape) {
    base = nestedShape.interfaceName;
  } else {
    const map: Record<PropertyType, string> = {
      string: "string",
      number: "number",
      boolean: "boolean",
      "string[]": "string[]",
      "number[]": "number[]",
      object: "Record<string, unknown>",
      unknown: "unknown",
    };
    base = map[type] ?? "unknown";
  }
  return isNullable ? `${base} | null` : base;
}

// ---------------------------------------------------------------------------
// 1. Types file — includes nested interfaces
// ---------------------------------------------------------------------------

function generateTypesFile(schema: WidgetSchema): string {
  const { widgetName, properties } = schema;

  // Collect unique nested shapes
  const nestedShapes = new Map<string, NestedObjectShape>();
  for (const p of properties) {
    if (p.nestedShape) {
      nestedShapes.set(p.nestedShape.interfaceName, p.nestedShape);
    }
  }

  // Nested interfaces first
  const nestedInterfaces = Array.from(nestedShapes.values())
    .map((shape) => {
      const fields = shape.fields
        .map((f) => `  ${f.name}${f.isNullable ? "?" : ""}: ${f.type === "string" ? "string" : "unknown"};`)
        .join("\n");
      return `export interface ${shape.interfaceName} {\n${fields}\n}`;
    })
    .join("\n\n");

  // Main props interface
  const propLines = properties
    .map((p) => {
      const comment = p.description
        ? `  /** ${p.description}${p.renderHint !== "text" ? ` [${p.renderHint}]` : ""} */\n`
        : p.renderHint === "html"
        ? `  /** Rendered as HTML (dangerouslySetInnerHTML) */\n`
        : "";
      const optional = p.isNullable ? "?" : "";
      return `${comment}  ${p.camelName}${optional}: ${tsType(p.type, p.nestedShape, false)};`;
    })
    .join("\n");

  return `// Auto-generated by Sitefinity Widget Studio — v0.2
// Source: ${schema.className} (${schema.sourceType})
// Do not edit manually — re-run the converter to update.
${nestedInterfaces ? `\n${nestedInterfaces}\n` : ""}
export interface ${widgetName}Props {
${propLines}
}
`;
}

// ---------------------------------------------------------------------------
// 2. Metadata file
// ---------------------------------------------------------------------------

function generateMetadataFile(schema: WidgetSchema): string {
  const { widgetName, properties, razorMetadata } = schema;

  const metaEntries = properties
    .map((p) => {
      const lines: string[] = [
        `    type: "${p.type}"`,
        `    renderHint: "${p.renderHint}"`,
      ];
      if (p.displayName) lines.push(`    displayName: "${p.displayName}"`);
      if (p.description) lines.push(`    description: "${p.description}"`);
      if (p.defaultValue !== undefined && p.defaultValue !== null) {
        const val =
          typeof p.defaultValue === "string"
            ? `"${p.defaultValue}"`
            : String(p.defaultValue);
        lines.push(`    defaultValue: ${val}`);
      }
      if (p.section) lines.push(`    section: "${p.section}"`);
      if (p.isNullable) lines.push(`    isNullable: true`);
      return `  ${p.camelName}: {\n${lines.join(",\n")},\n  }`;
    })
    .join(",\n");

  const razorNotes = razorMetadata
    ? `
// Razor metadata detected from view:
// - Partial views: ${razorMetadata.partialViews.join(", ") || "none"}
// - Animation libraries: ${razorMetadata.animationLibraries.join(", ") || "none"}
// - Root CSS classes: ${razorMetadata.cssClasses.join(", ") || "none"}
// - HTML-rendered props: ${razorMetadata.hasHtmlRawProps.join(", ") || "none"}`
    : "";

  return `// Auto-generated by Sitefinity Widget Studio — v0.2
// Source: ${schema.className} (${schema.sourceType})
${razorNotes}

export const ${widgetName[0].toLowerCase() + widgetName.slice(1)}Metadata = {
${metaEntries},
} as const;
`;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function generateWidget(schema: WidgetSchema): GeneratedWidget {
  const { widgetName } = schema;

  // v0.3 SDK-compatible outputs (primary)
  const entityFile = generateEntityFile(schema);
  const componentFile = generateNextjsComponent(schema);
  const registryEntrySnippet = generateRegistryEntry(schema);

  return {
    // v0.3 primary outputs
    entityFile,
    componentFile,
    registryEntrySnippet,
    // v0.2 deprecated outputs — kept for backward compat
    typesFile: {
      filename: `${widgetName}.types.ts`,
      content: generateTypesFile(schema),
    },
    metadataFile: {
      filename: `${widgetName}.metadata.ts`,
      content: generateMetadataFile(schema),
    },
  };
}
