import { WidgetRegistry, initRegistry, defaultWidgetRegistry } from '@progress/sitefinity-nextjs-sdk';

// ─── Register converted widgets here ─────────────────────────────────────────
//
// After generating a widget in the studio converter, place the generated files
// in src/app/widgets/<widget-name>/ then uncomment and add an entry below.
//
// Example — after converting CustomImage_MVC:
//
//   import { CustomImageMVC } from './widgets/custom-image-mvc/custom-image-mvc';
//   import { CustomImageMVCEntity } from './widgets/custom-image-mvc/custom-image-mvc.entity';
//
// Then inside widgets: {}:
//
//   'CustomImage_MVC': {
//       componentType: CustomImageMVC,
//       entity: CustomImageMVCEntity,
//       ssr: true
//   }
//
// The key must match the original Sitefinity toolbox Name (the string key from
// the registry entry snippet generated by the studio — not the TS identifier).
// ─────────────────────────────────────────────────────────────────────────────

const customWidgetRegistry: WidgetRegistry = {
    widgets: {
        // converted widgets go here
    },
};

Object.keys(defaultWidgetRegistry.widgets).forEach((key) => {
    customWidgetRegistry.widgets[key] = defaultWidgetRegistry.widgets[key];
});

export const widgetRegistry: WidgetRegistry = initRegistry(customWidgetRegistry);
